### ISSUE TITLE
Using SetContentView for RecylerView is causing the disappearance of ToolBar

### ISSUE THREAD

**Issue by VishnuSanal** [allexandresampaio/RSS-AndroidApp#1]
https://github.com/allexandresampaio/RSS-AndroidApp/blob/80f00bc5ab8f6c4e075fae25604be983a1dfec2a/app/src/main/java/br/ufpe/cin/android/rss/MainActivity.java#L127

**Comment by allexandresampaio** [comment]
Thank you @VishnuSanal for reviewing the issue, now it's fixed.
