### ISSUE TITLE
Resolução do problema de apagar a toolbar

### ISSUE THREAD

**Issue by leopoldomt** [allexandresampaio/RSS-AndroidApp#2]
Você tem de comentar as seguintes linhas: 

https://github.com/allexandresampaio/RSS-AndroidApp/blob/add208b4a9cb558e968f253e7f45625c65f36796/app/src/main/java/br/ufpe/cin/android/rss/MainActivity.java#L51 - o `RecyclerView` deve ser obtido a partir do layout, ao invés de ser criado do zero. 

E, mais importante: https://github.com/allexandresampaio/RSS-AndroidApp/blob/add208b4a9cb558e968f253e7f45625c65f36796/app/src/main/java/br/ufpe/cin/android/rss/MainActivity.java#L128 - nesta linha você está efetivamente dizendo que quer que a sua tela toda seja apenas um `RecyclerView` (o que foi criado na linha 51).

**Comment by allexandresampaio** [comment]
Agora que entendi o erro, pareceu simples demais que não sei como passou assim despercebido hahaha. 
Obrigado pela ajuda, professor!
